{
  "comments": [
    {
      "key": {
        "uuid": "9adffdf1_e92c8b04",
        "filename": "hv-collector-dcae-app-simulator/src/main/kotlin/org/onap/dcae/collectors/veshv/simulators/dcaeapp/impl/MessageStreamValidation.kt",
        "patchSetId": 11
      },
      "lineNbr": 63,
      "author": {
        "id": 3701
      },
      "writtenOn": "2018-12-04T12:14:57Z",
      "side": 1,
      "message": "You forgot to log error message, i.e. ${ex.localizedMessage}",
      "revId": "b565b26edc725662ababd94304eca5e65e6dc004",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9adffdf1_c9398742",
        "filename": "hv-collector-dcae-app-simulator/src/main/kotlin/org/onap/dcae/collectors/veshv/simulators/dcaeapp/impl/MessageStreamValidation.kt",
        "patchSetId": 11
      },
      "lineNbr": 64,
      "author": {
        "id": 3701
      },
      "writtenOn": "2018-12-04T12:14:57Z",
      "side": 1,
      "message": "Debug method has variant which I believe prints stacktrace for you (to avoid this \"it.cause.getOrElse\") \n```\nfun debug(message: String, t: Throwable)\n```\nso the usage would simply be\n```\nlogger.debug(\"Detailed stack trace\", ex)\n```",
      "revId": "b565b26edc725662ababd94304eca5e65e6dc004",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9adffdf1_69409ba5",
        "filename": "hv-collector-dcae-app-simulator/src/main/kotlin/org/onap/dcae/collectors/veshv/simulators/dcaeapp/impl/adapters/DcaeAppApiServer.kt",
        "patchSetId": 11
      },
      "lineNbr": 96,
      "author": {
        "id": 3701
      },
      "writtenOn": "2018-12-04T12:14:57Z",
      "side": 1,
      "message": "The addition of \"received\" word does not make this log clear",
      "revId": "b565b26edc725662ababd94304eca5e65e6dc004",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}